package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"

	"github.com/google/uuid"
	"github.com/jessedearing/service-catalog/graph/model"
	"github.com/jessedearing/service-catalog/internal/metrics"
	"github.com/jessedearing/service-catalog/internal/vars"
)

// Services is the resolver for the services field.
func (r *queryResolver) Services(ctx context.Context, page *int) ([]*model.Service, error) {
	fin := metrics.RecordQuery("services")
	defer fin("2")
	db, err := vars.GetDBFromContext(ctx)
	if err != nil {
		fin("5")
		return nil, err
	}

	pg := 1
	if page != nil {
		pg = *page
	}
	services, err := db.All(ctx, pg)
	if err != nil {
		fin("5")
		return nil, err
	}

	return services, err
}

// Service is the resolver for the service field.
func (r *queryResolver) Service(ctx context.Context, id uuid.UUID) (*model.Service, error) {
	fin := metrics.RecordQuery("service")
	defer fin("2")
	db, err := vars.GetDBFromContext(ctx)
	if err != nil {
		fin("5")
		return nil, err
	}

	service, err := db.FindByID(ctx, id)
	if err != nil {
		fin("5")
		return nil, err
	}
	return service, err
}

// SearchByName is the resolver for the searchByName field.
func (r *queryResolver) SearchByName(ctx context.Context, name string) ([]*model.Service, error) {
	fin := metrics.RecordQuery("searchByName")
	defer fin("2")
	db, err := vars.GetDBFromContext(ctx)
	if err != nil {
		fin("5")
		return nil, err
	}

	services, err := db.FindByName(ctx, name)
	if err != nil {
		fin("5")
		return nil, err
	}
	return services, err
}

// SearchAll is the resolver for the searchAll field.
func (r *queryResolver) SearchAll(ctx context.Context, query string) ([]*model.Service, error) {
	fin := metrics.RecordQuery("searchAll")
	defer fin("2")
	db, err := vars.GetDBFromContext(ctx)
	if err != nil {
		fin("5")
		return nil, err
	}

	services, err := db.SearchAll(ctx, query)
	if err != nil {
		fin("5")
		return nil, err
	}

	return services, err
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
