package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jessedearing/service-catalog/graph/model"
)

// Services is the resolver for the services field.
func (r *queryResolver) Services(ctx context.Context, page *int) ([]*model.Service, error) {
	panic(fmt.Errorf("not implemented: Services - services"))
}

// Service is the resolver for the service field.
func (r *queryResolver) Service(ctx context.Context, id uuid.UUID) (*model.Service, error) {
	panic(fmt.Errorf("not implemented: Service - service"))
}

// SearchByName is the resolver for the searchByName field.
func (r *queryResolver) SearchByName(ctx context.Context, name string) ([]*model.Service, error) {
	panic(fmt.Errorf("not implemented: SearchByName - searchByName"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
