// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Query struct {
}

type Service struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Versions    []*Version `json:"versions"`
}

type Version struct {
	ID      uuid.UUID `json:"id"`
	Version string    `json:"version"`
}
