// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Service struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Versions []*Version `json:"versions"`
}

type Version struct {
	ID      string `json:"id"`
	Version string `json:"version"`
}
